# Generated by Django 4.0 on 2022-01-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAccountManager',
        ),
    ]
