# Generated by Django 4.0 on 2022-01-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_product_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
