# Generated by Django 4.0 on 2022-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variation'),
        ('cart', '0002_alter_cart_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='product.Variation'),
        ),
    ]
