# Generated by Django 4.0 on 2022-04-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default=None, max_length=10),
        ),
    ]
