# Generated by Django 4.0 on 2022-04-03 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variation'),
        ('order', '0002_remove_orderdetail_color_remove_orderdetail_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='variation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.variation'),
        ),
    ]
