# Generated by Django 4.0 on 2022-04-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variation'),
        ('order', '0003_alter_orderdetail_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='variation',
            field=models.ManyToManyField(blank=True, to='product.Variation'),
        ),
    ]
